### ISSUE TITLE
테스트 설계 다시 공부

### ISSUE THREAD

**Issue by zhyunk** [zhyun-project/simple-board-02#79]
### 테스트 수행 목적
- 결함의 제거가 아닌 발견을 목적으로 함
- 개발 설계 시 부터 테스트를 고려

### 개발 단계별 테스트 분류
- 단위 테스트: 구현 단계에서 구현한 모듈의 단위로 테스트를 수행. 모듈이 단독적으로 실행할 수 있는 환경 필요

- 통합 테스트: 단위 테스트가 완료된 모듈 간의 상호작용(인터페이스)이 올바르게 되는지를 테스트
	- 개별적인 모듈에 대한 테스트 진행 후 놓친 부분 보완
	- 모듈의 통합 과정에서 오류가 발생되는지를 확인
	- 모듈간의 예기치 못한 상호 작용 때문에 발생하는 부작용(side effect)으로 인한 오류 발생 부분 확인

> 참고: https://blog.naver.com/wisestone2007/221334008864

<br>

### TODO
- [ ] #83
  - [x] service 테스트 정리 
  - [x] interface 테스트 정리
  - [ ] test container 정리

<br>

#### user-module, article-module

<table>
<thead>
<tr><td>

- [x] #81

</td><td>

- [x] #82

</td></tr>
</thead>
<tbody>
<tr>
<td>

- respository
  - table에 데이터 입력/수정/삭제 확인

</td>
<td>

- respository
  - table에 데이터 입력/수정/삭제 확인

</td>
</tr>
<tr>
<td>

- service
  - 기능별 동작 확인 

</td>
<td>

- service
  - 기능별 동작 확인 

</td>
</tr>
<tr>
<td>

- business
  - 기능별 동작 확인

</td>
<td>

- business
  - 기능별 동작 확인

</td>
</tr>
<tr>
<td>

- controller
  - api path 확인
  - request 값 확인

</td>
<td>

- controller
  - api path 확인
  - request 값 확인

</td>
</tr>
</tbody>
</table>

#### controller 실행 테스트

<table>
<thead>
<tr><td>

- [x] #81 

</td><td>

- [x] #82 

</td></tr>
</thead>
<tbody>
<tr>
<td>

- 정상 상황 응답 출력 확인, db 데이터 확인

</td>
<td>

- 정상 상황 응답 출력 확인, db 데이터 확인

</td>
</tr>
<tr>
<td>

- ~~예외 상황 응답 출력 확인, db 데이터 확인~~

</td>
<td>

- ~~예외 상황 응답 출력 확인, db 데이터 확인~~

</td>
</tr>
<tr>
<td colspan=2 align=center>

통합 테스트를 이렇게 하는게 맞는가에 대한 깊은 고민에 빠져서 정상 상황 응답 출력만 확인하고 말았다. 🤔  
통합 테스트에 대해 조금 더 알아보는 것으로!    

</td>
</tr>

</tbody>
</table>

**Comment by zhyunk** [comment]
https://inf.run/C3fC

강의를 구매 +_+

**Comment by zhyunk** [comment]
수행 기간을 5월 4일까지에서 12일까지로 늘림 +_+

**Comment by zhyunk** [comment]
수행 기간을 5월 12일까지에서 17일까지로 늘림 😔
12일까지 user 모듈에 대한 테스트는 마무리 되었다 
내일부터 article 모듈도 화이팅 💪😬 

개인적으로 시작하길 잘 한것 같고 조급해 할 필요가 전혀 없는것 같다 
조급하면 집중만 더 안됨
🦆

**Comment by zhyunk** [comment]
rest controller를 test하는 2가지 방법
- https://howtodoinjava.com/spring-boot2/testing/rest-controller-unit-test-example/#:~:text=Test%20a%20Spring%20Boot%20REST%20Controller%20with%20JUnit,4.%20Best%20Practices%20...%205%205.%20Conclusion%20
  - WebMvcTest or using Mockito

**Comment by zhyunk** [comment]
> rest controller를 test하는 2가지 방법
> 
> * https://howtodoinjava.com/spring-boot2/testing/rest-controller-unit-test-example/#:~:text=Test%20a%20Spring%20Boot%20REST%20Controller%20with%20JUnit,4.%20Best%20Practices%20...%205%205.%20Conclusion%20
>   
>   * WebMvcTest or using Mockito

오늘 퇴근하면 user rest controller 단위 테스트 코드를 mockito를 사용하는 mock 검증으로 바꿔볼까!
