### ISSUE TITLE
user module test

### ISSUE THREAD

**Issue by zhyunk** [zhyun-project/simple-board-02#81]
### 단위 테스트

- respository
  - table에 데이터 입력/수정/삭제 확인
- service
  - 기능별 동작 확인 
- business
  - 기능별 동작 확인
- controller
  - api path 확인
  - request 값 확인 
- filter (05/17 추가)
  - 동작 확인

#### TODO
- [x] respository
  -  [`UserRepositoryTest`](https://github.com/zhyun-project/simple-board-02/blob/feature/REFACTOR-MODULE/simpleBoard02/b-server-user/src/test/java/kim/zhyun/serveruser/domain/member/repository/UserRepositoryTest.java), [`SessionUserRepositoryTest`](https://github.com/zhyun-project/simple-board-02/blob/feature/REFACTOR-MODULE/simpleBoard02/b-server-user/src/test/java/kim/zhyun/serveruser/domain/signup/repository/SessionUserRepositoryTest.java)
- [x] service
  - [x] email service [`EmailServiceTest`](https://github.com/zhyun-project/simple-board-02/blob/feature/REFACTOR-MODULE/simpleBoard02/b-server-user/src/test/java/kim/zhyun/serveruser/domain/signup/service/EmailServiceTest.java)
    - [x] redis 에서 email 존재 여부 반환
    - [x] 매일 전송
    - [x] redis에 메일 인증코드 저장
    - [x] session user에 email 할당
  - [x] session user service
  - [x] signup service
  - [x] member service
- [x] business
  - [x] sign up business
  - [x] member business
- [x] controller
  - [x] check api controller
  - [x] sign api controller
  - [x] member api controller
- [x] filter
  - [x] authenticatoin filter
  - [x] session check filter

---

#### controller 실행 테스트

- [x] 정상 상황 응답 출력 확인, db 데이터 확인
- ~~[ ] 예외 상황 응답 출력 확인, db 데이터 확인~~
